NDefines.NNationDesigner.POINTS_AVAILABLE = 5000
NDefines.NNationDesigner.RULER_BASE_AGE = 30					-- Creating a ruler with this age is free.
NDefines.NNationDesigner.RULER_MIN_AGE = 18						--
NDefines.NNationDesigner.RULER_MAX_AGE = 50
NDefines.NNationDesigner.HEIR_BASE_AGE = 15	--
NDefines.NNationDesigner.HEIR_MIN_AGE = 0
NDefines.NNationDesigner.HEIR_MAX_AGE = 30
NDefines.NNationDesigner.CONSORT_MIN_AGE = 18
NDefines.NNationDesigner.CONSORT_MAX_AGE = 50
NDefines.NNationDesigner.RULER_BASE_SKILL = 3					-- This ruler skill level is free.
NDefines.NNationDesigner.RULER_MAX_SKILL = 7
NDefines.NNationDesigner.RULER_SKILL_COST_MODIFIER = 2.5					-- .
NDefines.NNationDesigner.ELECTION_SKILL_COST_MODIFIER = 0.25			-- If government has elections apply this to cost of rulers
NDefines.NNationDesigner.CONSORT_COST_MULTIPLIER = 0.25			-- Consorts cost is multiplied by this
NDefines.NNationDesigner.BASE_TAX_COST_MODIFIER = 0.5
NDefines.NNationDesigner.PRODUCTION_COST_MODIFIER = 0.5
NDefines.NNationDesigner.MANPOWER_COST_MODIFIER = 0.5
NDefines.NNationDesigner.GOLD_PROVINCE_COST_MULTIPLIER = 3
NDefines.NNationDesigner.TECH_GROUP_COST_MODIFIER = 1
NDefines.NNationDesigner.MEMBER_OF_HRE_COST = 25				-- Cost for being part of the HRE (base)
NDefines.NNationDesigner.MEMBER_OF_HRE_PROVINCE_COST = 0.25		-- Cost for being part of the HRE (extra cost multiplier on provinces)
NDefines.NNationDesigner.TECH_GROUP_NO_NEIGHBOUR_COST = 25		-- If no neighbour of this tech group cost is increased by this amount
NDefines.NNationDesigner.IDEAS_PERCENTAGE_LIMIT = 50			-- Max % from any one category to not get overstacking penalty
NDefines.NNationDesigner.IDEAS_LIMIT_PENALTY = 5				-- All ideas are this much more expensive for overstacking (at 100% stacking)
NDefines.NNationDesigner.IDEAS_LEVEL_COST_1 = 0					-- Can be overriden in script
NDefines.NNationDesigner.IDEAS_LEVEL_COST_2 = 5
NDefines.NNationDesigner.IDEAS_LEVEL_COST_3 = 15
NDefines.NNationDesigner.IDEAS_LEVEL_COST_4 = 30
NDefines.NNationDesigner.IDEAS_LEVEL_COST_5 = 50
NDefines.NNationDesigner.IDEAS_LEVEL_COST_6 = 75
NDefines.NNationDesigner.IDEAS_LEVEL_COST_7 = 105
NDefines.NNationDesigner.IDEAS_LEVEL_COST_8 = 140
NDefines.NNationDesigner.IDEAS_LEVEL_COST_9 = 180
NDefines.NNationDesigner.IDEAS_LEVEL_COST_10 = 225
NDefines.NNationDesigner.IDEAS_MAX_LEVEL = 4					-- Can be overriden in script
NDefines.NNationDesigner.FLAT_TAX_AMOUNT = 4					-- How much tax per province in 'flat' option
NDefines.NNationDesigner.FLAT_MP_AMOUNT = 3						-- How much manpower per province in 'flat' option
NDefines.NNationDesigner.MAX_DISTANCE_TO_OWNER_AREA = 500
NDefines.NNationDesigner.MAX_DISCOVERED_PROVINCE_DISTANCE = 700
NDefines.NNationDesigner.DEFAULT_MALE_CHANCE = 75				-- Default chance for males if ruler and heir start genders aren't the same.
NDefines.NNationDesigner.ALL_FEMALE_MALE_CHANCE = 0				-- Chance for males if starting ruler and heir were both female.
NDefines.NNationDesigner.ALL_MALE_MALE_CHANCE = 100				-- Chance for females if starting ruler and heir were both male.
NDefines.NNationDesigner.MAX_GOVERNMENT_RANK = 10
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_1 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_2 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_3 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_4 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_5 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_6 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_7 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_8 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_9 = 0
NDefines.NNationDesigner.GOVERNMENT_RANK_COST_10 = 0