NDefines.NReligion.PIETY_CORRUPTION = -2.5
NDefines.NReligion.PIETY_MANPOWER = 2.5
NDefines.NReligion.PIETY_COST = 0.50
NDefines.NReligion.PIETY_ABS_THRESHOLD = 0.75
NDefines.NReligion.PIETY_ACTION_COOLDOWN = 5
NDefines.NReligion.CONSECRATE_PATRIACH_AUTHORITY_BOOST = 0.05 --5% or so
NDefines.NReligion.CONSECRATE_PATRIARCH_THRESHOLD = 30 --in development
NDefines.NReligion.ORTHODOX_ICON_DURATION_MONTHS = 300
NDefines.NReligion.ORTHODOX_ICON_AUTHORITY_COST = 0.25
NDefines.NReligion.MAYA_COLLAPSE_PROVINCES = 10	-- Maya collapses to this size on reform
NDefines.NReligion.MAYA_COLLAPSE_PROVINCES_PER_REFORM = 3					-- Maya keeps this many extra provinces per reform
NDefines.NReligion.YEARLY_DOOM_INCREASE = 0.5								-- Multiplied by number of provinces
NDefines.NReligion.DOOM_REDUCTION_FROM_REFORMS = 0.5						-- This much less monthly doom (as a fraction of whole) for each reform passed
NDefines.NReligion.DOOM_REDUCTION_FROM_OCCUPATION = 0.05					-- Multiplied by development
NDefines.NReligion.DOOM_REDUCTION_FROM_BATTLE = 1							-- Per 1000 men killed
NDefines.NReligion.DOOM_REDUCTION_FROM_SACRIFICE = 1						-- Multiplied by power
NDefines.NReligion.SACRIFICE_COOLDOWN = 5									-- Years before you can sacrifice a ruler/heir from same country
NDefines.NReligion.SACRIFICE_LIBERTY_DESIRE = 25							-- LD added from sacrifice (ruler)
NDefines.NReligion.SACRIFICE_LIBERTY_DESIRE_HEIR = 20						-- LD added from sacrifice (heir)
NDefines.NReligion.AUTHORITY_FROM_DEVELOPMENT = 0.02							-- Multiplied by development (affected by autonomy)
NDefines.NReligion.AUTHORITY_FROM_AUTONOMY = 0.2							-- Authority loss from granting autonomy
NDefines.NReligion.RELIGIOUS_LEAGUE_COOLDOWN = 5								-- Minimum years between joining/leaving religious league
NDefines.NReligion.RELIGIOUS_LEAGUE_WAR_BONUS_DURATION = 100					-- How many years the 'Joined League War' bonus lasts
NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 3						-- The number of spawned centers of reformation wont exceed this number
NDefines.NReligion.MAX_RELIGIOUS_CENTER_SPREAD_DISTANCE = 500.0				-- When spreading the religion to other provinces the distance wont exceed this number
NDefines.NReligion.CONVERSION_ZEAL_DURATION = 10950							-- Amount of days in which you cannot convert the province back.
NDefines.NReligion.KARMA_FOR_CONVERSION = 0.1
NDefines.NReligion.MIN_CARDINALS = 7											-- Least amount of cardinals/ Starting cardinals
NDefines.NReligion.MAX_CARDINALS = 49											-- Max amount of cardinals
NDefines.NReligion.MAX_CARDINALS_PER_COUNTRY = 7								-- Max cardinals in a single country
NDefines.NReligion.YEARLY_PAPAL_INFLUENCE_CATHOLIC = 1.0						-- The amount of yearly papal influence you receive each year for being catholic
NDefines.NReligion.YEARLY_PAPAL_INFLUENCE_PER_CARDINAL = 0.5					-- The amount of yearly papal influence you receive each year for each cardinal you have active
NDefines.NReligion.YEARLY_POPE_INVESTED_INFLUENCE_PER_CARDINAL = 0.1			-- The amount of investment Papal state gets towards becoming Papal controller for each cardinal that exists
NDefines.NReligion.MAX_PAPAL_INFLUENCE = 999.0								-- The maximum stored amount of papal influence for each country.
NDefines.NReligion.REFORM_DESIRE_PER_YEAR = 0.005								-- Increase of reform descire for each year.
NDefines.NReligion.MINIMUM_DEVELOPMENT_ALLOWED = 10.0								-- You will need a higher development than this for your province to be eligible for cardinal
NDefines.NReligion.COUNTRY_DEVELOPMENT_DIVIDER = 200.0							-- When a cardinal is chosen the formula is diving a countrys development by this number.
NDefines.NReligion.INVEST_PAPAL_INFLUENCE = 10.0								-- The amount of papal influence you invest in becoming controller of the curia.
NDefines.NReligion.NUMBER_OF_POSSIBLE_CARDINALS = 10							-- Number of cardinals from said number of most successful provinces to be randomly picked from.
NDefines.NReligion.MAX_CHURCH_POWER = 999
NDefines.NReligion.ASPECT_REMOVE_COST = 1										-- Stabhit for removing an Aspect of Faith.
NDefines.NReligion.MAX_UNLOCKED_ASPECTS = 3									-- Maximum number of Aspects of Faith the player can have unlocked at once.
NDefines.NReligion.CHURCH_POWER_RATE_SCALE = 0.1								-- Scaling value for rate at which church power is gained.
NDefines.NReligion.KARMA_FOR_OFFENSIVE_WAR = -10
NDefines.NReligion.KARMA_FOR_HONORING_CTA = 25
NDefines.NReligion.KARMA_PER_RELEASED_PROVINCE = 1
NDefines.NReligion.KARMA_PER_TAKEN_PROVINCE = -1
NDefines.NReligion.KARMA_TOO_HIGH = 33
NDefines.NReligion.KARMA_TOO_LOW = -33
NDefines.NReligion.KARMA_JUST_RIGHT_HIGH = 33
NDefines.NReligion.KARMA_JUST_RIGHT_LOW = -33
NDefines.NReligion.KARMA_RESTORE_ON_RULER_DEATH = 25
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = -50
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 25
NDefines.NReligion.STARTING_HARMONY = 50.0							-- Confucian countries start with this.
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 1.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 1.0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -2.5
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.03 			-- 3%
NDefines.NReligion.INITIAL_ISOLATIONISM = 1						-- Level of isolationism for a newly shintoed country.
NDefines.NReligion.NOT_SAME_MUSLIM_SCHOOL_ALLIANCE_ACCEPTANCE = 35		-- Alliance acceptance value (positive and negative) for different religious schools
NDefines.NReligion.NOT_SAME_MUSLIM_SCHOOL_ROYAL_MARRIAGE_ACCEPTANCE = 35	-- Royal marriage acceptance (positive and negative) for different religious schools
NDefines.NReligion.SAME_MUSLIM_SCHOOL_ALLIANCE_ACCEPTANCE = 15			-- Alliance acceptance value for same religious schools
NDefines.NReligion.SAME_MUSLIM_SCHOOL_ROYAL_MARRIAGE_ACCEPTANCE = 15		-- Royal marriage acceptance for same religious schools
NDefines.NReligion.RELIGIOUS_CONVERSION_AUTONOMY_WEIGHT = 0.05			-- How much autonomy affects selection of province to spread religion to (from e.g. Centers of Reformation).
NDefines.NReligion.RELIGIOUS_CONVERSION_DEVELOPMENT_WEIGHT = 0.05			-- How much development affects selection of province to spread religion to (from e.g. Centers of Reformation).

NDefines.NReligion.COUNCIL_BASE_COST = 1000
NDefines.NReligion.COUNCIL_CARDINAL_SPREAD = 500
-- Papal Tithe defines
NDefines.NReligion.PAPAL_TITHE_MINIMUM_DIVISION_OF_LAND = 0.1				-- Minimum percentage to be used for the division of land in the yearly tithe calculation
NDefines.NReligion.PAPAL_TITHE_PERCENTAGE = 0.1							-- Percentage of the tithe I know tithe stands for a tenth but gamebalance is also important
NDefines.NReligion.PAPAL_TITHE_YEARLY_LEVEL_1 = 100						-- Level of threshold for yearly curia tithe visual state
NDefines.NReligion.PAPAL_TITHE_YEARLY_LEVEL_2 = 250						-- Level of threshold for yearly curia tithe visual state
NDefines.NReligion.PAPAL_TITHE_YEARLY_LEVEL_3 = 800						-- Level of threshold for yearly curia tithe visual state
NDefines.NReligion.PAPAL_TITHE_YEARLY_LEVEL_4 = 1500						-- Level of threshold for yearly curia tithe visual state
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_COST = 0.5						-- Cost in years-of-income
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_TREASURY_CONTRIBUTION = 0.25	-- Amount of the cost of the Call for Ecumenical Council that goes in the Curia Treasury
NDefines.NReligion.BUY_INDULGENCE_COST = 0.5								-- Cost in years-of-income
NDefines.NReligion.BUY_INDULGENCE_COST_EXCOMMUNICATE_MULTIPLIER = 2.5		-- Multiplicative factor for excommunicated countries
NDefines.NReligion.BUY_INDULGENCE_DURATION = 5							-- Duration of the indulgence effect in numbers of years (Opinion modifier has is own decay defined)
NDefines.NReligion.BUY_INDULGENCE_TREASURY_CONTRIBUTION = 0.5				-- Amount of the cost of Buy Indulgence that goes in the Curia Treasury
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE = 10.0						-- Invested Influence given by appointing a cardinal
NDefines.NReligion.APPOINT_CARDINAL_CORRUPTION = 0.5						-- Corruption gained by the Papal State when appointing cardinals in its own land
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE_PAPAL_STATE = 1.0			-- Yearly passive influence gained by cardinals in Papal States
-- Appoint cardinal cost formula:
NDefines.NReligion.APPOINT_CARDINAL_TOTAL_FACTOR = 2.5						-- Factor to the number of total cardinals for the cost formula
NDefines.NReligion.APPOINT_CARDINAL_COUNTRY_FACTOR = 25					-- Factor to the number of cardinals in the target country for the cost formula
NDefines.NReligion.APPOINT_CARDINAL_MINIMUM_COST = 25.0					-- Minimum cost to appoint a cardinal
NDefines.NReligion.PICK_GOLDEN_BULL_COST = 500							-- Integer cost for pick a golden bull
NDefines.NReligion.REFORM_DESIRE_PROV_CONVERSION_SPEED_MODIFIER = 1